<?php
require_once '../config/db.php'; require_once 'auth.php';
$id=(int)($_GET['id']??0); $edit=$id>0;
$a=['category_id'=>'','name'=>'','description'=>'','location'=>'','opening_hours'=>'','best_time_to_visit'=>'','estimated_visit_duration'=>'','distance_km'=>'','travel_time'=>'','google_maps_link'=>'','road_condition'=>''];
if($edit){$s=$pdo->prepare('SELECT * FROM attractions WHERE attraction_id=?');$s->execute([$id]);$a=$s->fetch(PDO::FETCH_ASSOC);if(!$a)exit('Attraction not found.');}
$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST'){
  foreach(array_keys($a) as $k){if($k!=='attraction_id'&&$k!=='created_at')$a[$k]=trim($_POST[$k]??'');}
  if($a['name']==='')$errors[]='Name is required.';
  if($a['category_id']==='')$errors[]='Category is required.';
  if(!$errors){
    $fields=['category_id','name','description','location','opening_hours','best_time_to_visit','estimated_visit_duration','distance_km','travel_time','google_maps_link','road_condition'];
    if($edit){$set=implode(',',array_map(fn($k)=>"$k=?",$fields));$pdo->prepare("UPDATE attractions SET $set WHERE attraction_id=?")->execute(array_merge(array_map(fn($k)=>$a[$k],$fields),[$id]));}
    else{$cols=implode(',',$fields);$qs=implode(',',array_fill(0,count($fields),'?'));$pdo->prepare("INSERT INTO attractions($cols) VALUES($qs)")->execute(array_map(fn($k)=>$a[$k],$fields));}
    header('Location: attractions.php?saved=1');exit;
  }
}
$cats=$pdo->query('SELECT * FROM categories ORDER BY category_name')->fetchAll(PDO::FETCH_ASSOC);$pageTitle=$edit?'Edit Attraction':'Add Attraction';include 'header.php';
?><div class="form-card"><div class="form-intro"><h3><?=$pageTitle?></h3><p>Enter accurate information that visitors can use when planning their Hunnasgiriya day visit.</p></div><?php if($errors): ?><div class="alert error"><ul><?php foreach($errors as $e): ?><li><?=htmlspecialchars($e)?></li><?php endforeach; ?></ul></div><?php endif; ?><form method="post"><div class="form-grid"><div class="form-group"><label>Category *</label><select name="category_id" required><option value="">Select category</option><?php foreach($cats as $c): ?><option value="<?=$c['category_id']?>" <?=$a['category_id']==$c['category_id']?'selected':''?>><?=htmlspecialchars($c['category_name'])?></option><?php endforeach; ?></select></div><div class="form-group"><label>Name *</label><input name="name" value="<?=htmlspecialchars($a['name'])?>" required></div><div class="form-group full"><label>Description</label><textarea name="description" rows="5"><?=htmlspecialchars($a['description'])?></textarea></div><div class="form-group"><label>Location</label><input name="location" value="<?=htmlspecialchars($a['location'])?>"></div><div class="form-group"><label>Opening Hours</label><input name="opening_hours" value="<?=htmlspecialchars($a['opening_hours'])?>"></div><div class="form-group"><label>Best Time to Visit</label><input name="best_time_to_visit" value="<?=htmlspecialchars($a['best_time_to_visit'])?>"></div><div class="form-group"><label>Estimated Visit Duration</label><input name="estimated_visit_duration" value="<?=htmlspecialchars($a['estimated_visit_duration'])?>"></div><div class="form-group"><label>Distance (km)</label><input name="distance_km" value="<?=htmlspecialchars($a['distance_km'])?>"></div><div class="form-group"><label>Travel Time</label><input name="travel_time" value="<?=htmlspecialchars($a['travel_time'])?>"></div><div class="form-group full"><label>Google Maps Link</label><input type="url" name="google_maps_link" value="<?=htmlspecialchars($a['google_maps_link'])?>" placeholder="https://maps.google.com/..."></div><div class="form-group full"><label>Road Condition / Safety Notes</label><textarea name="road_condition" rows="4"><?=htmlspecialchars($a['road_condition'])?></textarea></div></div><div class="form-buttons"><button class="btn" type="submit">Save Attraction</button><a class="btn secondary" href="attractions.php">Cancel</a></div></form></div><?php include 'footer.php'; ?>
